### ISSUE TITLE
1.12 crash trying to launch (java.lang.NullPointerException)

### ISSUE THREAD

**Issue by Starra** [Furgl/Stupid-Things#10]
At least I _think_ it's Stupid Things causing this. It might be another mod and I could be wasting your time (in which case I apologise!).

It says there's a problem with the tooltip helper? Maybe?

java.lang.NullPointerException: Initializing game
	at furgl.stupidThings.util.TooltipHelper.addTooltip(TooltipHelper.java:40)

https://paste.ee/p/XPqWO

**Comment by Furgl** [comment]
It looks like this was caused by Stupid Things, thanks for telling me! Try this and see if it's fixed: 
[Stupid Things-1.12-1.1.4.jar.zip](https://github.com/Furgl/Stupid-Things/files/1714002/Stupid.Things-1.12-1.1.4.jar.zip)

**Comment by Starra** [comment]
Yep, that seems to have worked and I can load things up again. Thank you very much for the quick response!
