### ISSUE TITLE
problem with conflict with industrial foregoing

### ISSUE THREAD

**Issue by violetkitty87** [Furgl/Stupid-Things#12]
i currently have your mod in my modpack called frisky business beyond worlds and the conflict is that its asking for artificial dyes from industrial foregoing in which those dyes are kinda a pain in the butt to get and there is no way in the config to fix that
![2018-10-29_20 08 48](https://user-images.githubusercontent.com/13909869/47687480-d4788880-dbb6-11e8-8e11-edaa6e08a641.png)
![2018-10-29_20 11 11](https://user-images.githubusercontent.com/13909869/47687481-d5a9b580-dbb6-11e8-8172-95e9fc04d58b.png)

**Comment by Furgl** [comment]
It uses dyes from any mod.

**Comment by violetkitty87** [comment]
its not letting me use any other one
