### ISSUE TITLE
The improved hoes feature not working

### ISSUE THREAD

**Issue by Dimentive** [Furgl/Stupid-Things#14]
Right-clicking or shift-right-clicking ground with any vanilla hoe only tills one block, even though all the improved hoe options are set to `true` in stupidthings.cfg.

#### Versions

* **Minecraft:** 1.12.2
* **Forge:** 14.23.5.2825 (latest)
* **Stupid Things:** [1.1.5](https://minecraft.curseforge.com/projects/stupid-things/files/2530785) (latest)

**Comment by Furgl** [comment]
Stupid Things does not change vanilla hoe behavior, it adds new hoes with more functionality
