### ISSUE TITLE
Crash w/ JEI

### ISSUE THREAD

**Issue by WenXin20** [Furgl/Stupid-Things#15]
Forge v14.23.5.2838
Stupid Things v1.1.5
JEI v4.15.0.285

I got a crash after typing `bucket` into JEI's search bar and clicking to the third page.
[Crash Report](http://paste.dimdev.org/ogufawaxoy.mccrash)

**Comment by WenXin20** [comment]
Edit: It also seems like the crash just randomly happens while mousing over other items, even when there are no items from this mod showing in JEI. At the time, I was looking at items from the Pyrotech mod.

**Comment by Furgl** [comment]
Fixed in v1.1.6
