### ISSUE TITLE
Crash while crafting Betweenlands buckets

### ISSUE THREAD

**Issue by LuciaCHuygens** [Furgl/Stupid-Things#16]
Hello,

I already posted an issue over at Angry-Pixel's (because the issue happened with a Betweenlands bucket) & one of their developers pointed out that the problem was a missing null check in Stupid Things.
Please see: https://github.com/Angry-Pixel/The-Betweenlands/issues/866

**Comment by Coji4000** [comment]
I am having this issue as well in MC Eternal Pack which contains both mods.

**Comment by adam9899** [comment]
> I am having this issue as well in MC Eternal Pack which contains both mods.

Oh me too!

**Comment by Coji4000** [comment]
if anyone stumbles across this issue the fix is to disable acid and rubber from the stupid things config

**Comment by Furgl** [comment]
Fixed in v1.1.6
