### ISSUE TITLE
Improved Hoe client crash

### ISSUE THREAD

**Issue by blairwilson** [Furgl/Stupid-Things#19]
MC Eternal modpack V1.3.2
Stupid Things V1.12.X-1.1.5
Left clicking on plants causes this client crash. Was done on an MP server.
https://paste.dimdev.org/pejupuveze.mccrash

**Comment by itanshi** [comment]
confirm https://paste.dimdev.org/wovedebuso.mccrash

**Comment by Furgl** [comment]
Fixed in v1.1.6
