### ISSUE TITLE
[Suggestion] Use static entry name for configuration

### ISSUE THREAD

**Issue by SeraphJACK** [Furgl/Stupid-Things#21]
# Synopsis

Currently, the configurations controlling game objects registries are using the localized name as the configuration entry name, thus these entries would possibly change if players switched the language, causing lots of issues and even caused the game to crash (CFPAOrg/I18nUpdateMod#33 #20).

**Code involved:**

https://github.com/Furgl/Stupid-Things/blob/b7b3d1dd228f894dfac5a8ce807e4b99d36520b9/src/main/java/furgl/stupidThings/common/item/ModItems.java#L92

https://github.com/Furgl/Stupid-Things/blob/b7b3d1dd228f894dfac5a8ce807e4b99d36520b9/src/main/java/furgl/stupidThings/common/block/ModBlocks.java#L51

https://github.com/Furgl/Stupid-Things/blob/b7b3d1dd228f894dfac5a8ce807e4b99d36520b9/src/main/java/furgl/stupidThings/common/config/Config.java#L28

# Suggestion

Use static strings(i.e. registry name) as the configuration entry name, instead of the localized names. For instance, replace the `I18n.translateToLocal` expressions with `item/block.getRegistryName()`.

# Remarks

Please keep in mind that localized names should **never** have any effect on the internal logic of the game.

**Comment by Furgl** [comment]
Thank you for the suggestion - using localized names was not a very good idea on my part! Fixed in v1.1.6
