### ISSUE TITLE
(Stupid Things-1.10.2-1.1) Crash when fire with the block bomb blaster

### ISSUE THREAD

**Issue by BuckTheWeasel** [Furgl/Stupid-Things#3]
crashes when fire blocks 

crashlog here : https://pastebin.com/RRvybC2e
I think it a crash with Hwyla mod.

**Comment by Furgl** [comment]
Thank you for bringing this to my attention. I attached a version where it should be fixed. If it's still not fixed, you can post another crash log and I'll look into it again. I'll add this fix to the next public update as well.
[Stupid Things-1.10.2-1.1-Fix.jar.zip](https://github.com/Furgl/Stupid-Things/files/1086422/Stupid.Things-1.10.2-1.1-Fix.jar.zip)

**Comment by BuckTheWeasel** [comment]
it has been fixed thanks 👍
