### ISSUE TITLE
1.12 Bug - Smoke Bombs & Balloons In All Creative Tabs

### ISSUE THREAD

**Issue by ghost** [Furgl/Stupid-Things#4]
Every creative tab has the smoke bombs and all types of balloons in them.

**Comment by Furgl** [comment]
Thanks for bringing this up! This is fixed in v1.1.2:
[Stupid Things-1.12-1.1.2.jar.zip](https://github.com/Furgl/Stupid-Things/files/1216445/Stupid.Things-1.12-1.1.2.jar.zip)
