### ISSUE TITLE
1.12.1 crash when using block bomb launcher

### ISSUE THREAD

**Issue by cheesecakegangster** [Furgl/Stupid-Things#8]
I saw you've had this issue before in 1.10, looks like it might have something to do with hwyla again?

<details>
  <summary>Crash report: (click to expand)</summary>
---- Minecraft Crash Report ----

WARNING: coremods are present:
  Inventory Tweaks Coremod (InventoryTweaks-1.63+beta.108.jar)
  TransformerLoader (OpenComputers-MC1.12.1-1.7.0.12.jar)
  ForgelinPlugin (Forgelin-1.5.1.jar)
  IELoadingPlugin (ImmersiveEngineering-0.12-71.jar)
  SignPictureCorePlugin (SignPicture-1.12.1-2.8.1-universal.jar)
  BCModPlugin (backpacks 1.12.1 - 3.3.2.jar)
Contact their authors BEFORE contacting forge

// Would you like a cupcake?

Time: 9/24/17 2:35 PM
Description: Saving entity NBT

java.lang.NullPointerException: Saving entity NBT
	at furgl.stupidThings.common.entity.EntityBlockBomb.func_70014_b(EntityBlockBomb.java:58)
	at net.minecraft.entity.Entity.func_189511_e(Entity.java:1739)
	at mcp.mobius.waila.api.impl.DataAccessorCommon.getNBTData(DataAccessorCommon.java:162)
	at net.darkhax.wawla.engine.waila.EntityProvider.getWailaOverride(EntityProvider.java:22)
	at mcp.mobius.waila.overlay.RayTracing.getIdentifierEntity(RayTracing.java:107)
	at mcp.mobius.waila.overlay.RayTracing.getTargetEntity(RayTracing.java:68)
	at mcp.mobius.waila.overlay.WailaTickHandler.tickClient(WailaTickHandler.java:104)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_389_WailaTickHandler_tickClient_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:342)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1706)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at furgl.stupidThings.common.entity.EntityBlockBomb.func_70014_b(EntityBlockBomb.java:58)

-- Entity being saved --
Details:
	Entity Type: stupidthings:blockbomb (furgl.stupidThings.common.entity.EntityBlockBomb)
	Entity ID: 610
	Entity Name: entity.blockBomb.name
	Entity's Exact location: 192.58, 66.52, 224.75
	Entity's Block location: World: (192,66,224), Chunk: (at 0,4,0 in 12,14; contains blocks 192,0,224 to 207,255,239), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 1.38, -0.06, -2.61
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.entity.Entity.func_189511_e(Entity.java:1739)
	at mcp.mobius.waila.api.impl.DataAccessorCommon.getNBTData(DataAccessorCommon.java:162)
	at net.darkhax.wawla.engine.waila.EntityProvider.getWailaOverride(EntityProvider.java:22)
	at mcp.mobius.waila.overlay.RayTracing.getIdentifierEntity(RayTracing.java:107)
	at mcp.mobius.waila.overlay.RayTracing.getTargetEntity(RayTracing.java:68)
	at mcp.mobius.waila.overlay.WailaTickHandler.tickClient(WailaTickHandler.java:104)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_389_WailaTickHandler_tickClient_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:342)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['ikbendusan'/445, l='MpServer', x=192.58, y=65.00, z=224.75]]
	Chunk stats: MultiplayerChunkCache: 437, 437
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (208,64,248), Chunk: (at 0,4,8 in 13,15; contains blocks 208,0,240 to 223,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 54825 game time, 94825 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 134 total; [EntityCreeper['Creeper'/266, l='MpServer', x=270.50, y=65.00, z=145.50], EntityDoge['Doge'/267, l='MpServer', x=261.96, y=64.00, z=174.29], EntitySheep['Sheep'/268, l='MpServer', x=265.21, y=66.00, z=245.45], EntitySheep['Sheep'/270, l='MpServer', x=260.50, y=70.00, z=285.50], EntitySheep['Sheep'/271, l='MpServer', x=261.50, y=70.00, z=286.50], EntitySheep['Sheep'/272, l='MpServer', x=262.50, y=69.00, z=290.22], EntitySheep['Sheep'/273, l='MpServer', x=258.73, y=71.00, z=289.49], EntityCow['Cow'/60, l='MpServer', x=121.19, y=95.00, z=167.56], EntityCow['Cow'/61, l='MpServer', x=122.50, y=96.00, z=167.50], EntityCow['Cow'/62, l='MpServer', x=121.50, y=97.00, z=165.50], EntityCow['Cow'/63, l='MpServer', x=133.19, y=100.00, z=171.24], EntityCreeper['Creeper'/64, l='MpServer', x=121.50, y=25.00, z=179.50], EntityZombie['Zombie'/65, l='MpServer', x=112.50, y=21.00, z=189.50], EntityZombie['Zombie'/66, l='MpServer', x=112.50, y=21.00, z=189.50], EntityBat['Bat'/67, l='MpServer', x=114.50, y=19.47, z=194.78], EntityCreeper['Creeper'/68, l='MpServer', x=127.50, y=18.00, z=215.50], EntityZombie['Zombie'/77, l='MpServer', x=123.73, y=62.00, z=173.50], EntityBat['Bat'/78, l='MpServer', x=141.66, y=21.19, z=185.08], EntityBat['Bat'/79, l='MpServer', x=142.25, y=20.57, z=185.91], EntityBat['Bat'/80, l='MpServer', x=132.06, y=20.78, z=191.72], EntityCreeper['Creeper'/81, l='MpServer', x=141.50, y=100.00, z=178.50], EntityZombie['Zombie'/82, l='MpServer', x=134.80, y=19.00, z=193.49], EntityCreeper['Creeper'/83, l='MpServer', x=128.50, y=18.00, z=216.50], EntityCow['Cow'/84, l='MpServer', x=137.78, y=73.00, z=221.50], EntityCow['Cow'/85, l='MpServer', x=141.45, y=71.00, z=222.57], EntityZombieVillager['Zombie Villager'/86, l='MpServer', x=134.50, y=20.00, z=239.50], EntitySpider['Spider'/598, l='MpServer', x=124.50, y=66.00, z=191.50], EntityCow['Cow'/87, l='MpServer', x=139.50, y=63.00, z=244.50], EntityCreeper['Creeper'/599, l='MpServer', x=117.50, y=66.00, z=196.50], EntityCow['Cow'/88, l='MpServer', x=141.50, y=63.00, z=240.50], EntityCow['Cow'/89, l='MpServer', x=138.50, y=63.00, z=242.50], EntityZombie['Zombie'/90, l='MpServer', x=136.79, y=64.00, z=250.72], EntityZombie['Zombie'/91, l='MpServer', x=134.40, y=52.00, z=298.93], EntityCow['Cow'/93, l='MpServer', x=145.81, y=72.00, z=215.46], EntityCow['Cow'/94, l='MpServer', x=145.47, y=72.00, z=213.83], EntityItem['item.item.block_bomb_launcher'/606, l='MpServer', x=193.36, y=63.00, z=221.67], EntitySheep['Sheep'/95, l='MpServer', x=152.78, y=63.00, z=236.71], EntitySpider['Spider'/96, l='MpServer', x=157.50, y=17.00, z=268.50], EntityCreeper['Creeper'/97, l='MpServer', x=153.50, y=32.00, z=284.79], EntitySkeleton['Skeleton'/98, l='MpServer', x=149.30, y=52.00, z=272.50], EntityBlockBomb['entity.blockBomb.name'/610, l='MpServer', x=192.58, y=66.52, z=224.75], EntityCreeper['Creeper'/99, l='MpServer', x=156.48, y=33.00, z=288.81], EntityPig['Pig'/105, l='MpServer', x=168.72, y=63.00, z=190.05], EntitySheep['Sheep'/106, l='MpServer', x=171.76, y=64.00, z=191.50], EntitySheep['Sheep'/107, l='MpServer', x=167.62, y=64.00, z=195.79], EntitySheep['Sheep'/108, l='MpServer', x=161.56, y=63.00, z=210.24], EntityPig['Pig'/109, l='MpServer', x=156.70, y=63.00, z=237.50], EntityItem['item.tile.sapling.oak'/110, l='MpServer', x=167.64, y=69.00, z=237.88], EntityItem['item.item.minecraft:apple'/111, l='MpServer', x=166.19, y=64.00, z=236.25], EntityWitch['Witch'/112, l='MpServer', x=170.31, y=64.00, z=224.51], EntitySkeleton['Skeleton'/113, l='MpServer', x=168.21, y=63.00, z=286.33], EntitySkeleton['Skeleton'/114, l='MpServer', x=165.26, y=63.00, z=277.51], EntityCreeper['Creeper'/115, l='MpServer', x=161.83, y=63.00, z=285.15], EntityBat['Bat'/120, l='MpServer', x=188.33, y=20.10, z=152.39], EntitySkeleton['Skeleton'/121, l='MpServer', x=182.45, y=26.00, z=198.73], EntityItem['item.tile.dirt.default'/122, l='MpServer', x=181.13, y=62.00, z=220.76], EntityItem['item.tile.dirt.default'/123, l='MpServer', x=180.36, y=63.00, z=222.41], EntityItem['item.tile.dirt.default'/124, l='MpServer', x=182.56, y=62.00, z=220.23], EntityItem['item.tile.dirt.default'/125, l='MpServer', x=180.78, y=62.00, z=219.76], EntityItem['item.tile.dirt.default'/126, l='MpServer', x=183.48, y=62.00, z=219.46], EntityItem['item.tile.dirt.default'/127, l='MpServer', x=184.88, y=62.00, z=220.88], EntityMinecartEmpty['entity.MinecartRideable.name'/128, l='MpServer', x=183.54, y=62.00, z=218.85], EntityItem['item.tile.dirt.default'/129, l='MpServer', x=185.88, y=62.00, z=220.88], EntityItem['item.tile.dirt.default'/130, l='MpServer', x=182.59, y=62.00, z=218.95], EntityItem['item.tile.dirt.default'/131, l='MpServer', x=180.13, y=63.00, z=218.13], EntityItem['item.tile.dirt.default'/132, l='MpServer', x=185.88, y=63.00, z=221.88], EntityItem['item.tile.rail_explosive'/133, l='MpServer', x=183.88, y=62.00, z=221.88], EntityItem['item.tile.rail_explosive'/134, l='MpServer', x=182.13, y=62.00, z=218.49], EntityItem['item.item.snowball'/135, l='MpServer', x=180.12, y=65.00, z=217.24], EntityCreeper['Creeper'/136, l='MpServer', x=185.81, y=44.00, z=230.44], EntityItem['item.tile.sapling.oak'/137, l='MpServer', x=178.16, y=73.00, z=227.90], EntityItemFrame['Item Frame'/393, l='MpServer', x=336.03, y=66.50, z=335.50], EntityItem['item.tile.sapling.oak'/138, l='MpServer', x=176.16, y=74.00, z=229.36], EntityCreeper['Creeper'/139, l='MpServer', x=186.18, y=51.00, z=250.52], EntityCreeper['Creeper'/140, l='MpServer', x=183.50, y=13.00, z=260.50], EntityPig['Pig'/141, l='MpServer', x=184.45, y=71.00, z=263.22], EntityCreeper['Creeper'/142, l='MpServer', x=186.21, y=67.00, z=304.53], EntityZombie['Zombie'/156, l='MpServer', x=204.50, y=41.00, z=168.50], EntitySquid['Squid'/157, l='MpServer', x=206.10, y=57.30, z=169.60], EntitySkeleton['Skeleton'/158, l='MpServer', x=194.48, y=47.00, z=201.59], EntityBat['Bat'/159, l='MpServer', x=204.25, y=54.10, z=206.54], EntityBalloon['entity.balloon.name'/160, l='MpServer', x=196.35, y=63.00, z=199.65], EntityBat['Bat'/161, l='MpServer', x=205.54, y=56.10, z=211.25], EntitySheep['Sheep'/162, l='MpServer', x=201.62, y=62.21, z=234.45], EntityBat['Bat'/163, l='MpServer', x=203.60, y=52.10, z=225.35], EntityItem['item.tile.flower2.poppy'/164, l='MpServer', x=201.13, y=63.00, z=228.50], EntityItem['item.tile.torch'/165, l='MpServer', x=199.13, y=62.00, z=231.87], EntityItem['item.item.immersiveengineering.seed.hemp'/166, l='MpServer', x=199.88, y=64.00, z=228.02], EntityPig['Pig'/167, l='MpServer', x=194.19, y=64.00, z=234.31], EntitySkeleton['Skeleton'/168, l='MpServer', x=203.50, y=69.00, z=271.50], EntitySkeleton['Skeleton'/169, l='MpServer', x=202.50, y=69.00, z=282.50], EntitySkeleton['Skeleton'/173, l='MpServer', x=212.50, y=40.00, z=167.50], EntityBat['Bat'/174, l='MpServer', x=222.55, y=52.10, z=169.53], EntityZombie['Zombie'/175, l='MpServer', x=217.70, y=63.00, z=181.20], EntityZombie['Zombie'/176, l='MpServer', x=209.50, y=63.00, z=179.50], EntityBalloon['entity.balloon.name'/177, l='MpServer', x=218.51, y=63.00, z=203.03], EntitySheep['Sheep'/178, l='MpServer', x=222.41, y=63.00, z=195.76], EntityCreeper['Creeper'/179, l='MpServer', x=212.31, y=51.00, z=209.50], EntityZombie['Zombie'/180, l='MpServer', x=205.75, y=55.00, z=215.55], EntityCreeper['Creeper'/181, l='MpServer', x=208.35, y=44.00, z=243.50], EntityZombie['Zombie'/182, l='MpServer', x=223.50, y=44.00, z=270.50], EntitySheep['Sheep'/183, l='MpServer', x=219.25, y=71.00, z=263.35], EntitySkeleton['Skeleton'/191, l='MpServer', x=224.50, y=32.00, z=158.50], EntitySkeleton['Skeleton'/192, l='MpServer', x=227.50, y=16.00, z=164.50], EntityCreeper['Creeper'/193, l='MpServer', x=232.50, y=63.00, z=170.50], EntitySkeleton['Skeleton'/194, l='MpServer', x=226.50, y=20.00, z=203.50], EntityPlayerSP['ikbendusan'/445, l='MpServer', x=192.58, y=65.00, z=224.75], EntitySkeleton['Skeleton'/195, l='MpServer', x=226.50, y=51.00, z=229.21], EntitySpider['Spider'/196, l='MpServer', x=228.03, y=50.00, z=226.01], EntityZombie['Zombie'/197, l='MpServer', x=231.50, y=49.00, z=226.50], EntityZombie['Zombie'/198, l='MpServer', x=234.50, y=49.00, z=226.50], EntityZombieVillager['Zombie Villager'/199, l='MpServer', x=232.50, y=49.00, z=226.50], EntitySheep['Sheep'/200, l='MpServer', x=238.23, y=65.00, z=234.66], EntitySheep['Sheep'/201, l='MpServer', x=231.54, y=67.00, z=246.75], EntityCreeper['Creeper'/202, l='MpServer', x=230.80, y=71.00, z=254.56], EntitySheep['Sheep'/203, l='MpServer', x=239.26, y=65.00, z=244.48], EntitySheep['Sheep'/204, l='MpServer', x=229.88, y=65.00, z=240.43], EntityZombie['Zombie'/205, l='MpServer', x=221.73, y=44.00, z=269.49], EntitySheep['Sheep'/206, l='MpServer', x=225.45, y=72.00, z=258.20], EntitySheep['Sheep'/207, l='MpServer', x=238.56, y=72.00, z=262.19], EntityBat['Bat'/208, l='MpServer', x=238.17, y=36.80, z=300.01], EntityCow['Cow'/209, l='MpServer', x=228.50, y=73.00, z=297.50], EntityCow['Cow'/210, l='MpServer', x=228.50, y=73.00, z=296.50], EntityCow['Cow'/211, l='MpServer', x=228.50, y=73.00, z=298.50], EntityCow['Cow'/212, l='MpServer', x=235.23, y=75.00, z=302.51], EntitySkeleton['Skeleton'/238, l='MpServer', x=246.28, y=52.00, z=192.51], EntitySheep['Sheep'/239, l='MpServer', x=252.62, y=64.00, z=238.13], EntitySheep['Sheep'/240, l='MpServer', x=255.23, y=65.00, z=242.72], EntitySheep['Sheep'/241, l='MpServer', x=249.79, y=66.00, z=253.48], EntitySheep['Sheep'/242, l='MpServer', x=237.79, y=65.00, z=242.58], EntitySheep['Sheep'/243, l='MpServer', x=242.50, y=70.00, z=256.27], EntityCow['Cow'/244, l='MpServer', x=246.50, y=75.00, z=302.50], EntityCow['Cow'/245, l='MpServer', x=246.50, y=75.00, z=303.50], EntityCow['Cow'/247, l='MpServer', x=243.53, y=76.00, z=301.85]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:524)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2748)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:418)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1086998472 bytes (1036 MB) / 2677321728 bytes (2553 MB) up to 5355339776 bytes (5107 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx5G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.41 Powered by Forge 14.22.1.2479 Optifine OptiFine_1.12.1_HD_U_C5 60 mods loaded, 60 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                      | Version               | Source                                        | Signature                                |
	|:--------- |:----------------------- |:--------------------- |:--------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft               | 1.12.1                | minecraft.jar                                 | None                                     |
	| UCHIJAAAA | mcp                     | 9.19                  | minecraft.jar                                 | None                                     |
	| UCHIJAAAA | FML                     | 8.0.99.99             | forge-1.12.1-14.22.1.2479.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge                   | 14.22.1.2479          | forge-1.12.1-14.22.1.2479.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | backpacks16840          | 3.3.2                 | backpacks 1.12.1 - 3.3.2.jar                  | None                                     |
	| UCHIJAAAA | opencomputers|core      | 1.7.0.12              | minecraft.jar                                 | None                                     |
	| UCHIJAAAA | bibliocraft             | 2.4.3                 | BiblioCraft[v2.4.3][MC1.12.0].jar             | None                                     |
	| UCHIJAAAA | chameleon               | 1.12-4.1.3            | Chameleon-1.12-4.1.3.jar                      | None                                     |
	| UCHIJAAAA | chesttransporter        | 2.8.7                 | ChestTransporter-1.12-2.8.7.jar               | None                                     |
	| UCHIJAAAA | codechickenlib          | 3.1.2.297             | CodeChickenLib-1.12-3.1.2.297-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | redstoneflux            | 2.0.1                 | RedstoneFlux-1.12-2.0.1.2-universal.jar       | d4f1503fbacd9b9fb767720420c5395104239ec9 |
	| UCHIJAAAA | cofhcore                | 4.3.5                 | CoFHCore-1.12-4.3.5.13-universal.jar          | None                                     |
	| UCHIJAAAA | cofhworld               | 1.0.1                 | CoFHWorld-1.12-1.0.1.8-universal.jar          | None                                     |
	| UCHIJAAAA | cyclopscore             | 0.10.17               | CyclopsCore-1.12-0.10.17.jar                  | None                                     |
	| UCHIJAAAA | colossalchests          | 1.6.5                 | ColossalChests-1.12-1.6.5.jar                 | None                                     |
	| UCHIJAAAA | eleccore                | 1.8.430               | ElecCore-1.12-1.8.430.jar                     | None                                     |
	| UCHIJAAAA | deepresonance           | 1.4.9                 | deepresonance-1.12-1.4.9.jar                  | None                                     |
	| UCHIJAAAA | deeznuts                | 1.0                   | DNCreeper-1.0.jar                             | None                                     |
	| UCHIJAAAA | easybreeding            | 5.0.0                 | easybreading-1.12-5.0.0.jar                   | None                                     |
	| UCHIJAAAA | waila                   | 1.8.20                | Hwyla-1.8.20-B35_1.12.jar                     | None                                     |
	| UCHIJAAAA | ffs                     | 1.12-2.1.2            | Fancy Fluid Storage-1.12-2.1.3.jar            | None                                     |
	| UCHIJAAAA | fastleafdecay           | v14                   | FastLeafDecay-v14.jar                         | None                                     |
	| UCHIJAAAA | forgelin                | 1.5.1                 | Forgelin-1.5.1.jar                            | None                                     |
	| UCHIJAAAA | gravestone              | 1.9.0                 | gravestone-1.9.0.jar                          | None                                     |
	| UCHIJAAAA | jei                     | 4.7.8.93              | jei_1.12.1-4.7.8.93.jar                       | None                                     |
	| UCHIJAAAA | mantle                  | 1.12-1.3.1.21         | Mantle-1.12-1.3.1.21.jar                      | None                                     |
	| UCHIJAAAA | tconstruct              | 1.12-2.7.3.30         | TConstruct-1.12-2.7.3.30.jar                  | None                                     |
	| UCHIJAAAA | immersiveengineering    | 0.12-71               | ImmersiveEngineering-0.12-71.jar              | None                                     |
	| UCHIJAAAA | immersivepetroleum      | 1.1.3                 | immersivepetroleum-1.12-1.1.3.jar             | None                                     |
	| UCHIJAAAA | immersivetech           | 1.3.1                 | immersivetech-1.12-1.3.1.jar                  | None                                     |
	| UCHIJAAAA | ic2                     | 2.8.16-ex112          | industrialcraft-2-2.8.16-ex112.jar            | de041f9f6187debbc77034a344134053277aa3b0 |
	| UCHIJAAAA | teslacorelib            | 1.0.8                 | tesla-core-lib-1.12-1.0.8.jar                 | None                                     |
	| UCHIJAAAA | industrialforegoing     | 1.12-1.12             | industrialforegoing-1.12-1.2.1-48.jar         | None                                     |
	| UCHIJAAAA | inventorytweaks         | 1.63+beta.108.6ff67c4 | InventoryTweaks-1.63+beta.108.jar             | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCHIJAAAA | jlgm_chatbox            | 1.2.0                 | jlgm_chatbox-1.12.1-1.2.0.jar                 | None                                     |
	| UCHIJAAAA | journeymap              | 1.12.1-5.5.0b3        | journeymap-1.12.1-5.5.0b3.jar                 | None                                     |
	| UCHIJAAAA | miab                    | 1.5.0.5               | MemeInABottle-1.5.0.5.jar                     | None                                     |
	| UCHIJAAAA | minecoprocessors        | 1.12.1-1.3            | minecoprocessors-1.12.1-1.3.jar               | None                                     |
	| UCHIJAAAA | mousetweaks             | 2.8                   | MouseTweaks-2.8-mc1.12.1.jar                  | None                                     |
	| UCHIJAAAA | opencomputers           | 1.7.0.12              | OpenComputers-MC1.12.1-1.7.0.12.jar           | None                                     |
	| UCHIJAAAA | harvestcraft            | 1.12.1b               | Pam's HarvestCraft 1.12.1b.jar                | None                                     |
	| UCHIJAAAA | chatping                | 3.0.8                 | ping-1.9-3.0.8.jar                            | None                                     |
	| UCHIJAAAA | rangedpumps             | 0.5                   | rangedpumps-0.5.jar                           | None                                     |
	| UCHIJAAAA | reborncore              | 3.3.0.99              | RebornCore-1.12.1-3.3.0.99-universal.jar      | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
	| UCHIJAAAA | storagedrawers          | 1.12-5.2.5            | StorageDrawers-1.12.1-5.3.2.jar               | None                                     |
	| UCHIJAAAA | refinedstorage          | 1.5.17                | refinedstorage-1.5.17.jar                     | None                                     |
	| UCHIJAAAA | rflux                   | 0.1.2                 | rflux-1.12-0.1.2.jar                          | None                                     |
	| UCHIJAAAA | signbutton              | 1.0                   | SignButton-1.12.0-1.0.jar                     | None                                     |
	| UCHIJAAAA | signpic                 | 2.8.1                 | SignPicture-1.12.1-2.8.1-universal.jar        | None                                     |
	| UCHIJAAAA | simplefluidtanks        | 1.12.1-1.7.0.0        | simplefluidtanks-1.12.1-1.7.0.0.jar           | None                                     |
	| UCHIJAAAA | stevescarts             | ${version}            | StevesCarts-1.12.1-2.4.8.44.jar               | None                                     |
	| UCHIJAAAA | stupidthings            | 1.1.3                 | Stupid Things-1.12-1.1.3.jar                  | None                                     |
	| UCHIJAAAA | thermalfoundation       | 2.3.5                 | ThermalFoundation-1.12-2.3.5.14-universal.jar | None                                     |
	| UCHIJAAAA | thermaldynamics         | 2.3.5                 | ThermalDynamics-1.12-2.3.5.12-universal.jar   | None                                     |
	| UCHIJAAAA | thermalexpansion        | 5.3.5                 | ThermalExpansion-1.12-5.3.5.19-universal.jar  | None                                     |
	| UCHIJAAAA | thutcore                | 5.11.0                | thutcore-5.11.0.jar                           | None                                     |
	| UCHIJAAAA | thuttech                | 6.0.4                 | thuttech-6.0.4.jar                            | None                                     |
	| UCHIJAAAA | torcharrowsmod          | 1.12.1-3              | torcharrows-1.12.1-3.jar                      | None                                     |
	| UCHIJAAAA | wawla                   | 2.5.241               | Wawla-1.12.1-2.5.241.jar                      | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJAAAA | teslacorelib_registries | 1.0.8                 | tesla-core-lib-1.12-1.0.8.jar                 | None                                     |

	Loaded coremods (and transformers): 
Inventory Tweaks Coremod (InventoryTweaks-1.63+beta.108.jar)
  invtweaks.forge.asm.ContainerTransformer
TransformerLoader (OpenComputers-MC1.12.1-1.7.0.12.jar)
  li.cil.oc.common.asm.ClassTransformer
ForgelinPlugin (Forgelin-1.5.1.jar)
  
IELoadingPlugin (ImmersiveEngineering-0.12-71.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
SignPictureCorePlugin (SignPicture-1.12.1-2.8.1-universal.jar)
  com.kamesuta.mc.signpic.asm.SignPictureTransformer
BCModPlugin (backpacks 1.12.1 - 3.3.2.jar)
  brad16840.common.asm.ClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 385.41' Renderer: 'GeForce GTX 970/PCIe/SSE2'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- wailaIntegration (Enabled/Not Forced)

	RebornCore: 
		Plugin Engine: 0
		RebornCore Version: 3.3.0.99
		Runtime Debofucsation 1
		RenderEngine: 1
	Launched Version: 1.12.1-forge1.12.1-14.22.1.2479
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 970/PCIe/SSE2 GL version 4.5.0 NVIDIA 385.41, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 12x Intel(R) Core(TM) i7-3930K CPU @ 3.20GHz
	OptiFine Version: OptiFine_1.12.1_HD_U_C5
	Render Distance Chunks: 10
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.0 NVIDIA 385.41
	OpenGlRenderer: GeForce GTX 970/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12
</details>

**Comment by cheesecakegangster** [comment]
tested it with hwyla removed, and it doesn't crash anymore, so definitely a problem there

**Comment by Furgl** [comment]
This has been fixed in v1.1.4. Thank you for reporting it!

**Comment by cheesecakegangster** [comment]
that was quick :D thanks for your time
